name: panvimdoc

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: stay-in-place
          description: Prevent the cursor from moving when using shift and filter actions.
          version: 'NVIM v0.7.0'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: auto generate docs'
          branch: ${{ github.head_ref }}
